### ISSUE TITLE
env variables $MY_PROXY and $MY_XTERN

### ISSUE THREAD

**Issue by vschiavoni** [columbia/crane#2]
The script apacheinstallbinapachectl relies on the existence of those two variables:

``` bash
# Start the application server
if [ $MY_XTERN"X" = "1X" ]; then
LD_PRELOAD=$XTERN_ROOT/dync_hook/interpose.so \
$MSMR_ROOT/apps/apache/install/bin/apachectl -f $MSMR_ROOT/eval/current/server7000/httpd7000.conf -k start &> ../server7000/${TEST_NAME}_0_${NO}_s${LOG_SUFFIX} &
REAL_SERVER_PID_0=$!
else
$MSMR_ROOT/apps/apache/install/bin/apachectl -f $MSMR_ROOT/eval/current/server7000/httpd7000.conf -k start &> ../server7000/${TEST_NAME}_0_${NO}_s${LOG_SUFFIX} &
REAL_SERVER_PID_0=$!
fi

echo "sleep some time"
sleep ${SLEEP_TIME}

# Start our proxy
if [ $MY_PROXY"X" = "1X" ]; then
${SERVER_PROGRAM} -n 0 -r -m s -c ${CONFIG_FILE} -l ./log 1>./log/node_0_${NO}_stdout 2>./log/node_0_${NO}_stderr &
fi
```

Those variables are defined by the eval.py script that generates the apacheinstallbinapachectl : 
https://github.com/columbia/crane/blob/master/eval/eval.py#L315
https://github.com/columbia/crane/blob/master/eval/eval.py#L324

Could you explain where those variables should point to ? 
Thanks

**Comment by hemingcui** [comment]
Hi Valerio,
    Thanks for your interests on Crane. The script you ran is already
obsolete. Please pull the crane repo and follow our latest crane/README.md
file on how to setup and run crane.

On Tue, Sep 15, 2015 at 7:54 PM, Valerio Schiavoni <notifications@github.com

**Comment by vschiavoni** [comment]
Closing my own issue, as this was obsolete.
