### ISSUE TITLE
hardcoded Columbia IPs in new-run.sh

### ISSUE THREAD

**Issue by vschiavoni** [columbia/crane#7]
Currently the new-run.sh file has hardcoded hostnames pointing to Columia machines:

``` python
# Update worker-run.py to the server
scp worker-run.py bug03.cs.columbia.edu:~/
scp worker-run.py bug01.cs.columbia.edu:~/
scp worker-run.py bug02.cs.columbia.edu:~/
```

How should we change those ? Without modifying those, executing the new-run one gets these:

```
Permission denied (publickey).
lost connection
Permission denied (publickey).
lost connection
Permission denied (publickey).
lost connection
Permission denied (publickey).
lost connection
```

**Comment by vschiavoni** [comment]
I've modified bug03 to point to u3 (my local LXC container running apache), bug01 to u1, and bug02 to u2. Is this the expected pattern ?

**Comment by hemingcui** [comment]
Dear Valerio,
    I recommend you keep using u1 on different replica, as our checkpoint
scripts use u1 as the container name. Keeping the same container name is
better for checkointing and restoring on different machines. I think a good
solution is use your own IPs instead of bug0x.cs.columbia.edu as the IPs.

**Comment by vschiavoni** [comment]
Thanks for the suggestion. This can be closed.
