### ISSUE TITLE
boost::interprocess::interprocess_exception with apache tests

### ISSUE THREAD

**Issue by vschiavoni** [columbia/crane#8]
In my current setup (more on this at the bottom), the execution of the command below fails:

```
./new-run.sh configs/apache.sh no_build proxy_only 1
```

In particular, the **ab** client cannot produce any performance benchmark.
By inspecting the logs, it boils down to the following error/problem:

```
ubuntu@ubuntu:~$ ./worker-run.py -a httpd -x 1 -p 1 -k 0 -c /home/ubuntu/crane -m s -i 0 --sp 1 --sd 1 --scmd 'rm /home/ubuntu/crane/apps/apache/install/logs/*; /home/ubuntu/crane/apps/apache/install/bin/apachectl   -f /home/ubuntu/crane/apps/apache/install/conf/httpd.conf -k start ' --tool none --enable-lxc yes --dmt-log-output 0 --start_proxy_only no --start_server_only yes
checking semphores...
Copy $MSMR_ROOT/eval-container/nodes.local.cfg to current folder
Copy default.options to current folder
Restarting the lxc container u1




XTERN is enabled. Preload library.
Replay real server command in lxc container:
parallel-ssh -l ubuntu -v -p 1 -x "-oStrictHostKeyChecking=no  -i ./.ssh/lxc_priv_key" -i -t 10 -h /home/ubuntu/crane/eval-container/u1 "/home/ubuntu/crane/xtern/scripts/wrap-xtern.sh 'rm /home/ubuntu/crane/apps/apache/install/logs/*; /home/ubuntu/crane/apps/apache/install/bin/apachectl   -f /home/ubuntu/crane/apps/apache/install/conf/httpd.conf -k start ' "
[1] 09:32:00 [FAILURE] 10.0.3.111 Exited with error code 134
Stderr: terminate called after throwing an instance of 'boost::interprocess::interprocess_exception'
  what():  No such file or directory
/home/ubuntu/crane/xtern/scripts/wrap-xtern.sh: line 6:  1713 Aborted                 rm /home/ubuntu/crane/apps/apache/install/logs/*
terminate called after throwing an instance of 'boost::interprocess::interprocess_exception'
  what():  No such file or directory
/home/ubuntu/crane/xtern/scripts/wrap-xtern.sh: line 6:  1714 Aborted                 /home/ubuntu/crane/apps/apache/install/bin/apachectl -f /home/ubuntu/crane/apps/apache/install/conf/httpd.conf -k start
```

The 'no such file or directory' is not clear to what it refers exactly. 
The u1 LXC container (into which the parallel-ssh command is executing to) has all the files. 
Have you already seen this ? 

I wonder if this is due to my current setup, and thus I'd be grateful if you could clarify something: is it possible to use Crane with services operating inside virtual machines (using KVM as hypervisor) ? 
Or else, there is a strict requirement for them to be physical machines ? 
In your evaluation (SOSP paper, section 7) you do specify the hardware spec of the replica machines, but not if those host virtual machines. 
Thanks !

**Comment by vschiavoni** [comment]
This seems to be solved. Close as invalid.

**Comment by hemingcui** [comment]
Dear Valerio,
    We have tested crane in both bare Linux OS and in LXC containers. I
don't think virtual machine would be an issue for Crane because our
implementation did not make any dependency with hypervisors. Maybe you
could just double check whether boost::interprocess works correctly in your
setting? Specifically, you could check the permissions in the /dev/shm/
directory or similar directories.

On Thu, May 26, 2016 at 9:43 PM, Valerio Schiavoni <notifications@github.com

**Comment by vschiavoni** [comment]
Hello,
here's the permission of /dev/shm:

```
ls -l /dev/shm
lrwxrwxrwx 1 root root 8 May 12 23:54 /dev/shm -> /run/shm
```
