### ISSUE TITLE
low throughput requests ?

### ISSUE THREAD

**Issue by vschiavoni** [columbia/crane#9]
Hi,
i've finally been able to setup a Crane cluster (1 client, 3 replicas) and launch 2 of  the benchmark scripts for Apache (./new-run.sh configs/apache.sh no_build orig 1, and ./new-run.sh configs/apache.sh no_build proxy_only 1). Interestingly, I get strangely low request rate results from ApacheBench.
In the case of `(./new-run.sh configs/apache.sh no_build orig`) I get:

```
Benchmarking 172.16.2.243 (be patient)


Server Software:        Apache/2.2.11
Server Hostname:        172.16.2.243
Server Port:            7000

Document Path:          /test.php
Document Length:        27 bytes

Concurrency Level:      8
Time taken for tests:   170.793 seconds
Complete requests:      1000
Failed requests:        0
Write errors:           0
Total transferred:      212000 bytes
HTML transferred:       27000 bytes
Requests per second:    5.86 [#/sec] (mean)
Time per request:       1366.340 [ms] (mean)
Time per request:       170.793 [ms] (mean, across all concurrent requests)
Transfer rate:          1.21 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.8      0      22
Processing:  1344 1364  28.8   1353    1542
Waiting:     1344 1364  28.8   1353    1542
Total:       1345 1365  28.8   1354    1543

Percentage of the requests served within a certain time (ms)
  50%   1354
  66%   1357
  75%   1365
  80%   1370
  90%   1394
  95%   1426
  98%   1472
  99%   1504
 100%   1543 (longest request)
```

In the case of `./new-run.sh configs/apache.sh no_build proxy_only 1`, I get:

```
Benchmarking 172.16.2.243 (be patient)


Server Software:        Apache/2.2.11
Server Hostname:        172.16.2.243
Server Port:            9000

Document Path:          /test.php
Document Length:        27 bytes

Concurrency Level:      8
Time taken for tests:   178.657 seconds
Complete requests:      1000
Failed requests:        0
Write errors:           0
Total transferred:      212000 bytes
HTML transferred:       27000 bytes
Requests per second:    5.60 [#/sec] (mean)
Time per request:       1429.260 [ms] (mean)
Time per request:       178.657 [ms] (mean, across all concurrent requests)
Transfer rate:          1.16 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.3      0       5
Processing:  1348 1424  90.4   1384    1853
Waiting:     1347 1423  90.3   1382    1852
Total:       1348 1424  90.4   1385    1853

Percentage of the requests served within a certain time (ms)
  50%   1385
  66%   1422
  75%   1460
  80%   1494
  90%   1565
  95%   1615
  98%   1673
  99%   1725
 100%   1853 (longest request)
```

In your SOSP paper there is not mention of the raw performances, and plots report relative results.
Do you mind sharing such numbers (even privately via email if you prefer)?

thanks

**Comment by hemingcui** [comment]
Dear Valerio,
    I found some sample raw evaluation results in our prior table. FYI.
Morevoer, I remember this result is just one of our workload settings on
running Apache. You can replace the php workload with other pages (static
pages, or node.js) to collect your performance results.

Server name Evaluation machine Performance metric Workload or benchmark
description No. of threads po Xtern only Proxy only Xtern + Proxy, seperate
scheduling Xtern + Proxy, joint scheduling Overhead of J/E Git version of
m-smr
Apache bug01 02 03(head) Response time Ab 8 195.885 ms 148.648 ms
202.653 ms 188.883
ms 249.256 ms b677bcae96ab4e25bfcbbfc957bc422da9bfe0fb
